title = "Makai"

base_url = "https://makai410.dev"

theme = "apollo"

compile_sass = true

# Tag
taxonomies = [{ name = "tags" }]
# Search
build_search_index = true
[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "OneHalfDark"

[extra]
use_cdn = false
theme = "dark"
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts[English]", url = "/english", weight = 1},
    { name = "/posts[Chinese]", url = "/chinese", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "hachyderm", url = "https://hachyderm.io/@makai410", icon = "mastodon" },
    { name = "github", url = "https://github.com/makai410/", icon = "github" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false