[[collection]]
type="box"
img="/assets/hunchgray.jpeg"
link="https://youtu.be/ugpywe34_30?si=DepIQE1z_95qDJ5j"
rotate=true
title="Hunch Gray"
subtitle="ZUTOMAYO"

[[collection]]
type="box"
img="/assets/timeleft.jpeg"
link="https://youtu.be/6OC92oxs4gA?si=nmSb5-k2iqx3GhN0"
rotate=true
title="Time Left"
subtitle="ZUTOMAYO"

[[collection]]
type="box"
img="/assets/milabo.jpeg"
link="https://youtu.be/I88PrE-KUPk?si=DRmHe76w5zEe-6sn"
rotate=true
title="Milabo"
subtitle="ZUTOMAYO"

[[collection]]
type="box"
img="/assets/mirrortune.jpeg"
link="https://youtu.be/BVvvUGP0MFw?si=hib-LywlARehzDBT"
rotate=true
title="Mirror Tune"
subtitle="ZUTOMAYO"
